Login page
ThibaultPaulmann/studyflow pull request #37
Opened 2022-09-01 22:34 UTC by Ola-Yeenca

Theres a little css problems conflicting with the homepage from the login/signup page... its a bit complicated and I'll get help from the teacher later today

2022-09-01 23:11 UTC, Ola-Yeenca commented
i will create a new pull request... just merge the master to my code.

2022-09-01 23:14 UTC, Ola-Yeenca commented
done now

2022-09-02 07:04 UTC, ThibaultPaulmann requested changes
There is also something weird now with all the pages where we seem to have given it double margins and it is not finding the background video so the whole site crashes
<img width="1792" alt="Screenshot 2022-09-02 at 09 03 55" src="https://user-images.githubusercontent.com/22735331/188078273-40f48136-b33d-4fbf-ab62-3774475ca27c.png">

2022-09-02 07:04 UTC, ThibaultPaulmann commented on app/views/shared/_navbar.html.erb
> -            <% if current_user.photo.present? %>
We shouldn't be deleting these file, they are essential for the avatar in the navbar that Mike did

2022-09-02 07:04 UTC, ThibaultPaulmann commented on app/views/shared/_navbar.html.erb
> -              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
you need to merge your thing with current master. If that doesn't work we'll have to manually rewrite this section

2022-09-02 07:06 UTC, Ola-Yeenca commented
I left a message on slack... with the video

2022-09-02 08:45 UTC, closed without merging